// Bit-exact parity test against the TypeScript prototype's xoroshiro128**
// PRNG (src/rng.ts). The golden values were captured from the TS
// implementation; if they ever drift, EITHER the C# port has a bug OR a
// deliberate change to determinism was made — both require explicit review
// per AGENTS.md §2 ("snapshots MUST be bit-exact").

using Wsr2.Engine;

namespace Wsr2.Engine.Tests;

public class RngParityTests
{
    /// <summary>
    /// First 8 uint64 outputs of the TS prototype's <c>Rng</c> for a handful
    /// of seeds. Generated by running the TS implementation directly.
    /// </summary>
    public static IEnumerable<object[]> GoldenSeeds() => new[]
    {
        new object[] { 42UL, new ulong[]
            {
                7631449856891427754UL,
                4306334408478191133UL,
                4482733528210176216UL,
                1183949725203728575UL,
                273771184284289554UL,
                3163695393723252040UL,
                12275746129726727310UL,
                3612110311052792287UL,
            }
        },
        new object[] { 1UL, new ulong[]
            {
                7280431682470476346UL,
                14368974704090626991UL,
                16882196638837869613UL,
                15386707582523340182UL,
                661144386810419178UL,
                12512432626221670171UL,
                12234347788108481103UL,
                15524541542696536261UL,
            }
        },
        new object[] { 123UL, new ulong[]
            {
                7183851293305883108UL,
                16949732023197691617UL,
                3916303367679974251UL,
                17745597361563480307UL,
                4954841383614479394UL,
                6719091343637911121UL,
                5985849707495174796UL,
                12464387511180488889UL,
            }
        },
    };

    [Theory]
    [MemberData(nameof(GoldenSeeds))]
    public void Next64_MatchesTypeScriptGoldenStream(ulong seed, ulong[] expected)
    {
        var rng = new Rng(seed);
        for (int i = 0; i < expected.Length; i++)
        {
            Assert.Equal(expected[i], rng.Next64());
        }
    }

    /// <summary>
    /// 53-bit floats from the TS prototype, captured the same way. Asserting
    /// these bit-exactly catches any drift in the (Next64()&gt;&gt;11)/2^53
    /// arithmetic on top of Next64 parity.
    /// </summary>
    [Fact]
    public void NextDouble_MatchesTypeScriptGoldenStream_Seed42()
    {
        var rng = new Rng(42UL);
        var expected = new[]
        {
            0.41370172570279384,
            0.23344685605605664,
            0.24300947149795415,
            0.06418204320897491,
            0.014841165638247777,
            0.17150427094785659,
            0.665469531136512,
            0.1958128923250364,
        };
        foreach (var d in expected)
        {
            Assert.Equal(d, rng.NextDouble());
        }
    }

    /// <summary>Snapshot/restore must be bit-exact (AGENTS.md §2).</summary>
    [Fact]
    public void Snapshot_RoundTrip_IsBitExact()
    {
        var rng = new Rng(123UL);
        for (int i = 0; i < 50; i++) { rng.NextDouble(); }
        var snap = rng.Snapshot();
        var nextOriginal = rng.NextDouble();

        var restored = new Rng(snap);
        Assert.Equal(nextOriginal, restored.NextDouble());
    }

    /// <summary>
    /// Snapshot of seed 123 after exactly 8 Next64 calls must match what the
    /// TS prototype reports.
    /// </summary>
    [Fact]
    public void Snapshot_AfterKnownDraws_MatchesTypeScript()
    {
        var rng = new Rng(123UL);
        for (int i = 0; i < 4; i++) { rng.NextDouble(); }
        var snap = rng.Snapshot();
        Assert.Equal("15286677830763768115", snap.S0);
        Assert.Equal("13913461560104057183", snap.S1);
    }

    [Fact]
    public void SameSeed_TwoInstances_ProduceIdenticalStreams()
    {
        var a = new Rng(42UL);
        var b = new Rng(42UL);
        for (int i = 0; i < 256; i++)
        {
            Assert.Equal(a.Next64(), b.Next64());
        }
    }

    [Fact]
    public void NextInt_RejectsBadInputs()
    {
        var r = new Rng(1UL);
        Assert.Throws<ArgumentOutOfRangeException>(() => r.NextInt(0));
        Assert.Throws<ArgumentOutOfRangeException>(() => r.NextInt(-1));
    }

    [Fact]
    public void NextDouble_AlwaysInUnitInterval()
    {
        var r = new Rng(1UL);
        for (int i = 0; i < 10_000; i++)
        {
            var v = r.NextDouble();
            Assert.InRange(v, 0.0, 1.0);
            Assert.NotEqual(1.0, v);
        }
    }
}
